FROM tier/grouper-training-env:base

LABEL author="tier-packaging@internet2.edu <tier-packaging@internet2.edu>" \
      Vendor="TIER" \
      ImageType="Grouper Training" \
      ImageName=$imagename \
      ImageOS=centos7

ENV USERTOKEN=ex211.1.1

# Nothing else needed for this exercise. Start empty and end empty
