#! /bin/bash
  
if [ ! -z "$1" ]
  then
    echo "Do not pass in an argument: $1"
fi
label=$( docker ps -a | grep 'tier/gte' | awk '{print $1}' )
docker exec -it -u tomcat "$label" /opt/grouper/grouperWebapp/WEB-INF/bin/gsh.sh 2> /dev/null
