#! /bin/bash
  
if [ -z "$1" ]
  then
    docker ps --format "{{.Names}} {{.Image}} {{.Status}}"
        exit 0
fi

docker exec -it -u tomcat "$1" /opt/grouper/grouperWebapp/WEB-INF/bin/gsh.sh 2> /dev/null
