ARG VERSION_TAG
FROM tier/gte:base-$VERSION_TAG

LABEL author="tier-packaging@internet2.edu <tier-packaging@internet2.edu>" \
      Vendor="TIER" \
      ImageType="Grouper Training" \
      ImageName=$imagename \
      ImageOS=centos7

ENV USERTOKEN=gte-301.4.1

# Nothing else needed for this exercise. Start empty and end empty
